# Generated by Django 6.0.1 on 2026-02-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_productdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='Category_Name',
            field=models.CharField(default='Uncategorized', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
