# Generated by Django 6.0.1 on 2026-02-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_productdb_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdb',
            name='Category_Name',
            field=models.CharField(max_length=100),
        ),
    ]
