# Generated by Django 6.0.1 on 2026-03-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WebApp", "0003_cartdb"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderDb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FirstName", models.CharField(blank=True, max_length=100, null=True)),
                ("LastName", models.CharField(blank=True, max_length=100, null=True)),
                ("Email", models.EmailField(blank=True, max_length=254, null=True)),
                ("Place", models.CharField(blank=True, max_length=100, null=True)),
                ("Address", models.CharField(blank=True, max_length=100, null=True)),
                ("Mobile", models.CharField(blank=True, max_length=11, null=True)),
                ("State", models.CharField(blank=True, max_length=100, null=True)),
                ("PinCode", models.CharField(blank=True, max_length=11, null=True)),
                ("TotalPrice", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
